### ISSUE TITLE
Community License expired.

### ISSUE THREAD

**Issue by rcemper** [jrpereirajr/interoperability-integratedml-adapter#1]
needs fix in Dockerfile

**Comment by jrpereirajr** [comment]
Done: https://github.com/jrpereirajr/interoperability-integratedml-adapter/commit/fcaac7b5ffd1b2901291d2fe6e856d7431a661cb

Thanks!

**Comment by rcemper** [comment]
thanks for the quick fix.
There is still a minor issue left on final owner in Dockerfile
PR placed

**Comment by jrpereirajr** [comment]
Thanks Mr. Robert!
